name: indus-waveform
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.12.0
  - pandas=2.2.0
  - matplotlib=3.8.2
  - plotly=5.19.0
  - opencv
  - scikit-learn=1.4.0
  - pip
  - pip:
    - streamlit==1.32.0
    - Pillow==10.2.0
    - python-multipart==0.0.6
